#include "custom_text/custom_text.hpp"
#include "display/display.hpp"
#include "graph/graph_build.cpp"
#include "grid/grid.hpp"
#include "quotes/quotes.hpp"
#include "text_list/text_list.hpp"
#include "time/time.hpp"
#include "window/window.hpp"